[package]
name = "sbb_model"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] } # for reading json-files
serde_json = "1.0" # for reading json-files
time = { path = "../time" }

