[package]
name = "sbb"
version = "0.1.0"
edition = "2021"
authors = ["Leon Sering <sering@math.ethz.ch"]

[lib]
name = "sbb"
path = "src/lib.rs"

[[bin]]
name = "sbb_bin"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
