[workspace]

members = [
    "time",
    "objective_framework",
    "model",
    "solution",
    "solver",
]

[workspace.package]
name = "sbb"
version = "0.2.0"
edition = "2021"
authors = ["Leon Sering <sering@math.ethz.ch"]
description = "Solving the rolling-stock scheduling with a local search approach."
