# Default Config File for General Parameters

duration_between_leistungen:
  # Minimal stop time at station
  minimal: PT19S
  # Turning time for spitzkehren (constant time added when rc-code is the same)
  wende: PT2M
  # Stop time added before and after betriebsfahrt
  betriebsfahrt: PT2M
  # Duration between Leistungen when "bedarf" changes
  kuppeln: PT2M
  # Minimal time between order-relevant arrival and departure events that can be chosen by SMT solver
  event: PT1M

objective:
  cost_per_fahrzeuggruppe_planned: 100
  cost_per_violated_reference_leistungsverknuepfung: 20
  continuous_idle_time:
    minimum: PT1H
    exponent: 1.1
    cost_factor: -5.0
  # soft constraint for the Wartungs-limiten
  bathtub:
    # 400 km deviation costs the equivalent of a violated reference verknuepfung
    marginal_cost_per_deceeded_km: 0.05
    marginal_cost_per_exceeded_km: 0.05
    # around 1 day deviation costs the equivalent of a violated reference verknuepfung
    marginal_cost_per_deceeded_second: 0.0002
    marginal_cost_per_exceeded_second: 0.0002
    # soft constraint for IVOG counters

ivog:
  duration: P30D
  # TODO: ARTRM-7 set to 12500.0 after refactoring
  distance: 125000.0
  bathtub:
    distance:
      ub: 12500
      lb: 0
    duration:
      ub: P20D
      lb: P10D
