[package]
name = "sbb_server"
authors.workspace = true
version.workspace = true
edition.workspace = true

[lib]
name = "sbb_server"
path = "src/lib.rs"

[[bin]]
name = "sbb_server"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sbb_solver = { path = "../solver" }
serde_json = { version = "1.0", features = ["preserve_order"]} # for reading json-files
axum = "0.7.3"
tokio = { version = "1.35.1", features = ["full"]} # web framework
