[package]
name = "time"
authors.workspace = true
version.workspace = true
edition.workspace = true

[lib]
name = "time"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
