[package]
name = "sbb_solver"
authors.workspace = true
version.workspace = true
edition.workspace = true

[lib]
name = "sbb_solver"
path = "src/lib.rs"

[[bin]]
name = "sbb_bin"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sbb_model = { path = "../model" }
itertools = "0.10"
im = "15.0.0" # for lazy copies of data structures
rayon = "1.5.1" # for parallel iterator
csv = "1.1"
